apply plugin: 'com.android.application'
android {
    compileSdkVersion 36
    namespace = "com.radial.client"

    defaultConfig {
        applicationId "com.radial.client"
        minSdkVersion 29
        targetSdkVersion 36
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
}

dependencies {
    implementation 'androidx.core:core:1.17.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
}
